/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.tweetcatch.view.swing;

import com.tweetcatch.model.TwitterAccount;
import com.tweetcatch.service.TweetService;
import com.tweetcatch.view.swing.dnd.DNDImagePanel;
import com.tweetcatch.view.swing.dnd.DNDSupport;
import com.tweetcatch.view.util.ScreenUtil;
import java.awt.GridLayout;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.io.File;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author c007329
 */
public class SendTweet extends javax.swing.JDialog {

    private TweetService tweetService = new TweetService();
    private List<TwitterAccount> twitterAccounts;
    private ScreenUtil screenUtil = new ScreenUtil();
    private List<DNDImagePanel> panels = new ArrayList<>();

    /**
     * Creates new form ManagerTweet
     */
    public SendTweet(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setIconImage(screenUtil.getImage("/image/if_Twitter_UI-15_2310210.png"));
        initParam();
        initBox();
        initPanelImages();
        this.pack();
    }

    private void initParam() {
        txtText.grabFocus();
        twitterAccounts = tweetService.getAccounts();
        if (twitterAccounts.isEmpty()) {
            JOptionPane.showMessageDialog(null, "You can't tweet, yet. You need registry a valid Twitter account.");
            btnSaveAndSend.setEnabled(false);
        } else {
            tweetService.setAccount(twitterAccounts.get(0));
        }
    }

    private void initPanelImages() {
        panelImages.setLayout(new GridLayout(2, 2));
        panelImages.setOpaque(false);
        panelImages.add(getDNDImagePane("image 1"));
        panelImages.add(getDNDImagePane("image 2"));
        panelImages.add(getDNDImagePane("image 3"));
        panelImages.add(getDNDImagePane("image 4"));

        DNDSupport bDNDSupport = new DNDSupport(this, panelImages);
        panelImages.addMouseListener(bDNDSupport);
        panelImages.addMouseMotionListener(bDNDSupport);
    }

    private void initBox() {
        twitterAccounts.forEach(twitterAccount -> boxAccounts.addItem(twitterAccount.getProfileName()));

        boxAccounts.addItemListener(new ItemListener() {
            @Override
            public void itemStateChanged(ItemEvent e) {
                if (e.getStateChange() == ItemEvent.SELECTED) {
                    tweetService.setAccount(getChooseTwitterAccount());
                }
            }
        });
    }

    private TwitterAccount getChooseTwitterAccount() {
        TwitterAccount account = null;
        for (TwitterAccount a : twitterAccounts) {
            if (a.getProfileName().equals(boxAccounts.getSelectedItem().toString())) {
                account = a;
                break;
            }
        }
        return account;
    }

    private DNDImagePanel getDNDImagePane(String title) {
        DNDImagePanel pane1 = new DNDImagePanel(title);
        panels.add(pane1);
        return pane1;
    }

    private List<File> getImages() {
        List<File> files = new ArrayList<>();
        for (DNDImagePanel panel : panels) {
            if (panel.getImage() != null) {
                files.add(panel.getImage());
            }
        }

        if (files.isEmpty()) {
            return null;
        } else {
            return files;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        boxAccounts = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtText = new javax.swing.JTextArea();
        btnSaveAndSend = new javax.swing.JButton();
        panelImages = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Send Tweet");

        jLabel1.setText("Twitter Account:");

        jLabel2.setText("Text:");

        txtText.setColumns(20);
        txtText.setRows(3);
        jScrollPane1.setViewportView(txtText);

        btnSaveAndSend.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/if_Save_Icon_1398916.png"))); // NOI18N
        btnSaveAndSend.setToolTipText("tweet and save");
        btnSaveAndSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveAndSendActionPerformed(evt);
            }
        });

        panelImages.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout panelImagesLayout = new javax.swing.GroupLayout(panelImages);
        panelImages.setLayout(panelImagesLayout);
        panelImagesLayout.setHorizontalGroup(
            panelImagesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelImagesLayout.setVerticalGroup(
            panelImagesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 257, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelImages, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(boxAccounts, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                        .addComponent(btnSaveAndSend, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(boxAccounts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnSaveAndSend))
                .addGap(10, 10, 10)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelImages, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveAndSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveAndSendActionPerformed
        //TwitterAccount account = getChooseTwitterAccount();
        try {
            List<File> images = getImages();
            tweetService.sendSimpleTweet(txtText.getText(), images);
            JOptionPane.showMessageDialog(rootPane, "Sended Tweet successfully"); 
            clear();
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        }

    }//GEN-LAST:event_btnSaveAndSendActionPerformed

    private void clear() {
        txtText.setText("");
        clearImages();
        //panels.clear();
        //panelImages.removeAll();
        //panelImages.repaint();
        txtText.grabFocus();
    }

    private void clearImages() {
        for (DNDImagePanel panel : panels) {
            panel.clear();
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SendTweet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SendTweet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SendTweet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SendTweet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SendTweet dialog = new SendTweet(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxAccounts;
    private javax.swing.JButton btnSaveAndSend;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelImages;
    private javax.swing.JTextArea txtText;
    // End of variables declaration//GEN-END:variables

}
